### ISSUE TITLE
Tracker: typescript support 

### ISSUE THREAD

**Issue by ibgreen** [uber-web/math.gl#80]
### v4.0? - Use typescript checking with adopting TS syntax

- [x] Run typescript checks on test directories #129 
- [x] Add typescript `.d.ts` files for all modules #129 
- [x] Add typescript `.d.ts` files for core module #129 

### v3.1 - Use typescript checking with adopting TS syntax

- [x] Improve type checking by adding JSDoc types in comments, if appropriate
- [x] Integrate ts checks in CI
- [x] Add soft ts for all modules
- [x] Add soft typescript checking of existing javascript code for core module

**Comment by Shayan-To** [comment]
When will this be available? I want to use `@math.gl/web-mercator` and I need typescript typings.

Is there anything that I can use right now?

**Comment by ibgreen** [comment]
Initial version published in `3.2.0-alpha.1`
